version: '2'

services:  
  mongo:
    image: mongo:3.4.3
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ${HOME}/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet